### ISSUE TITLE
Extension icon greyed out in toolbar.

### ISSUE THREAD

**Issue by Tech-Geek97** [PaulSec/Shodan-Firefox-Addon#12]
![ss+(2021-05-30+at+12 30 58)](https://user-images.githubusercontent.com/10946383/120114042-f0fc4900-c142-11eb-8298-a151c089b7d9.png)
The extension's icon is greyed out in the toolbar and does not function while clicked.
Attempted restarting Firefox and reinstalling extension, but the issue persists.

**Comment by catazoeker** [comment]
Having the same issue here on firefox and chrome.

**Comment by Tech-Geek97** [comment]
This seems to have resolved itself, I suspect a server side issue.

**Comment by ambarabacicicoco** [comment]
![immagine](https://user-images.githubusercontent.com/85345309/120795979-7b292080-c53a-11eb-8706-aab32f96496c.png)
