### ISSUE TITLE
Don't strip "www." from host names, but do strip port numbers

### ISSUE THREAD

**Issue by creideiki** [PaulSec/Shodan-Firefox-Addon#4]
When getting information about the visited site http://www.example.com/, the extension actually looks up the IP address for example.com, which isn't even guaranteed to exist, much less be the same as that of www.example.com. Additionally, if the URL includes a port number, it gets sent along in the lookup as well (as e.g. "example.com:81"), giving no results.

I'm very much not a JavaScript programmer, but some playing around with Firefox's console suggests that changing the regexp in [lib/main.js::queryDnsInformation()](https://github.com/PaulSec/Shodan-Firefox-Addon/blob/master/lib/main.js#L28) from `/https?:\/\/(?:www\.)?(.[^/]+).*/` to `/https?:\/\/([^/:]+)*/` gives a better result.

**Comment by PaulSec** [comment]
Hi there, 

Sorry for the late reply. I will check this out as soon as possible and provide a fix. 
Thanks for your feedback and the comment. It will not take long to provide it. 

Cheers,

**Comment by romainletendart** [comment]
Hi creideiki,

Thanks again for your feedback.
The issue is now fixed.

Cheers
