### ISSUE TITLE
Not Compatible with Multiprocess

### ISSUE THREAD

**Issue by GRMrGecko** [PaulSec/Shodan-Firefox-Addon#7]
FireFox Multiprocess is now available to the public, however add-ons must support it for it to function. This extension is one of the extensions I have which is blocking support, so I thought I would submit an issue on it.

**Comment by PaulSec** [comment]
We updated the version here: https://addons.mozilla.org/fr/firefox/addon/shodan-firefox-addon/
Enjoy! 👍
