### ISSUE TITLE
Update for Firefox 57 support

### ISSUE THREAD

**Issue by kmcquade** [PaulSec/Shodan-Firefox-Addon#9]
Marked as legacy extension in Firefox 57 and no longer works.

https://support.mozilla.org/en-US/kb/firefox-add-technology-modernizing

Please update. I love this extension!

**Comment by PaulSec** [comment]
We are currently looking into this :+1:

**Comment by PaulSec** [comment]
We updated the version here: https://addons.mozilla.org/fr/firefox/addon/shodan-firefox-addon/
Enjoy! 👍

**Comment by kmcquade** [comment]
Thanks!!
